title: ex ante
description: "Projects on probability and epistemology"
baseurl: ""
url: "https://alex94s.github.io/ex-ante/"
theme: jekyll-theme-primer

# Build settings
markdown: kramdown
source: docs
destination: docs/_site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
